aws_region          = "ap-south-1"
project_name        = "swiggy2"
project_environment = "production"
instance_type       = "t2.micro"
instance_ami        = "ami-0317b0f0a0144b137"
domain_name         = "ransite.live"
hostname            = "terraform-webserver"
